server.port=9992
spring.application.name=consult
spring.web.jackson.time-zone=America/Sao_Paulo
spring.web.jackson.default-property-inclusion=NON_NULL
spring.rabbitmq.host=localhost
spring.rabbitmq.password=guest
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.template.reply-timeout=60000
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=sid_project
spring.threads.virtual.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
fintech.messaging.consult.queue=queue-consult-rabbit
fintech.messaging.consult.reply-prefix=reply-consult-rabbit
