services:
  rabbitmq-broker:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq-broker
    environment:
      RABBIT_DEFINITIONS: rabbit_definitions.json
    ports:
      - "15672:15672"
      - "5672:5672"

  redis-service:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis-service
    ports:
      - "6379:6379"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-broker
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - rabbitmq-broker
      - redis-service
    ports:
      - "9991:9991"

  consult:
    build:
      context: ./consult
      dockerfile: Dockerfile
    container_name: consult
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-broker
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: sid_project
    depends_on:
      - rabbitmq-broker
      - redis-service
    ports:
      - "9992:9992"

  withdrawal:
    build:
      context: ./withdrawal
      dockerfile: Dockerfile
    container_name: withdrawal
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-broker
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: sid_project
    depends_on:
      - rabbitmq-broker
      - redis-service
    ports:
      - "9993:9993"
